### ISSUE TITLE
Video conferencing

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-rust#283]
I'm considering working on an open source meeting tool. It would be great if it could be a lightweight embedded plugin for Atomic-Server. If that's not possible, I'll probably use an external application. It should not overcomplicate Atomic Server in any way.

@jonassmedegaard told me about the [Janus](https://janus.conf.meetecho.com/) project, a WebRTC server written in C that focuses on being a really good broker for various connections. Seems really decent.

There's also [Pion](https://pion.ly/), written in Go. Is a bit more popular. Has some example full stack solutions, such as [Ion](https://github.com/pion/ion) or [peer-calls](https://github.com/peer-calls/peer-calls).

And [webrtc-rs](https://github.com/webrtc-rs/webrtc), a work in progress that aims to rewrite Pion. Since it's rust, it could potentially be embedded in Atomic-Server, which seems interesting.

**Comment by jonassmedegaard** [comment]
Technically there's no such thing as a "WebRTC server".
Using streaming media lingo, Janus is (mainly, among other things) a "Selective Forwarding Unit" (SFU).
Using more general networking terms, Janus acts as a broker for initiation of WebRTC sessions, and as a proxy or middle-man for the RTP  realtime streaming of those sessions.

The "server" part of a video conferencing setup is arguably instead the web pages glossing up the WebRTC stuff, presenting it as a "Web App" - similar to how a "webmail service" is not the backend iam or pop service, but the web pages and dynamic (server side or client side) code turning a web browsing experience into an email client connecting to a backend email server.

Here are some notes on various terms and features and front-end/backend/library implementations related to WebRTC: https://source.redpill.dk/media-stream-hosting/tree/DEVELOP.md

**Comment by jonassmedegaard** [comment]
Sorry, I realize that it can sound like needless nitpicking (and I still remember some 15 years ago someone correcting me for talking about my setting up a SIP server - "no, it is not a server, it is a router").

My point here is to help get you quicker from "hmm, let's try fit this strange new stuff into a common familar model" to "ahh, that's the model it is supposed to fit into, making it familiar in its own habitat".

**Comment by joepio** [comment]
Thanks for clarifying, @jonassmedegaard!

I'm still pretty intimidated to the set of abstractions required to get WebRTC working. I'll have to read way more to get a better understanding. I hope I'll find a relatively simple abstraction that helps me build a GUI for web conferencing, but so far I haven't found that.

**Comment by joepio** [comment]
Not gonna do this for now, closing
