### ISSUE TITLE
Docker build issue - compiled and copied binary can't be found / opened

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-rust#436]
Tried running the docker image, got this:

```
$ docker run -p 80:80 -p 443:443 -v atomic-storage:/atomic-storage --platform=linux/amd64 joepmeneer/atomic-server
exec /server/atomic-server-bin: no such file or directory
```

This should not happen. 

First I should fix the more abstract issue (how is an image pushed that does not work?) and then the more specific one.

Thanks to @rasendubi for reporting this

**Comment by joepio** [comment]
For some reason, the `COPY` command in the dockerfile isn't working:

```
# seems to work fine, which means the file is there
COPY --from=builder /app/target/release/atomic-server /server/atomic-server-bin
# throws an error!
file /server/atomic-server-bin
```

**Comment by rasendubi** [comment]
Could you try with `ls`? I think `file` might fail if there is an issue with linker (`/lib/ld-linux.so.2`)

**Comment by joepio** [comment]
If I remove `file` and simply try to open it, I get the same error: `file: not found`. 

I'm now trying some other files with the `COPY` command. Weird stuff.

**Comment by joepio** [comment]
But but... The file is there! I just can't open it. 

```
bash-5.1# ls -la
total 36064
drwxr-xr-x    1 root     root          4096 Jun 14 17:16 .
drwxr-xr-x    1 root     root          4096 Jun 14 17:16 ..
-rwxr-xr-x    1 root     root             0 Jun 14 17:16 .dockerenv
-rwxr-xr-x    1 root     root      36857616 Jun 14 17:16 atomic-server-bin
drwxr-xr-x    1 root     root          4096 May 24 16:32 bin
drwxr-xr-x    5 root     root           360 Jun 14 17:16 dev
drwxr-xr-x    1 root     root          4096 Jun 14 17:16 etc
drwxr-xr-x    2 root     root          4096 May 23 16:51 home
drwxr-xr-x    1 root     root          4096 May 24 16:32 lib
drwxr-xr-x    2 root     root          4096 May 24 16:32 lib64
drwxr-xr-x    5 root     root          4096 May 23 16:51 media
drwxr-xr-x    2 root     root          4096 May 23 16:51 mnt
drwxr-xr-x    2 root     root          4096 May 23 16:51 opt
dr-xr-xr-x  185 root     root             0 Jun 14 17:16 proc
drwx------    1 root     root          4096 May 24 16:32 root
drwxr-xr-x    2 root     root          4096 May 23 16:51 run
drwxr-xr-x    2 root     root          4096 May 23 16:51 sbin
drwxr-xr-x    2 root     root          4096 May 23 16:51 srv
dr-xr-xr-x   13 root     root             0 Jun 14 17:16 sys
drwxrwxrwt    2 root     root          4096 May 23 16:51 tmp
drwxr-xr-x    1 root     root          4096 May 24 16:32 usr
drwxr-xr-x    1 root     root          4096 May 23 16:51 var
bash-5.1# ./atomic-server-bin
bash: ./atomic-server-bin: No such file or directory
```

This is getting crazy.

**Comment by joepio** [comment]
> The best way to fix this is to use the same system type for build and run (so they have a similar set of libraries/linker)

Thanks @rasendubi !

Since I want to be able to build on my m1 mac, and run in the server in a lightweight image, I should still use a `builder` and `runner` step in my dockerfile. I'm not entirely sure what has changed to cause the docker build to fail, but I think I'll change some things. 

I tried getting rid of cargo-chef, as it caused some issues. Got me this minimal dockerfile:

```dockerfile
FROM rust as builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin atomic-server

# We only need a small runtime for this step, but make sure glibc is installed
FROM frolvlad/alpine-glibc as runtime
COPY --chmod=0755 --from=builder /app/target/release/atomic-server /atomic-server-bin
ENV ATOMIC_STORE_PATH="/atomic-storage/db"
ENV ATOMIC_CONFIG_PATH="/atomic-storage/config.toml"
ENV ATOMIC_PORT="80"
ENV ATOMIC_PORT_HTTPS="433"
ENTRYPOINT ["/atomic-server-bin"]
```

And even then the binary gave me `not found`.

```
/ # ./atomic-server-bin
sh: ./atomic-server-bin: not found
``

If I remove the `runtime`, so all happens on the same (large) image, I think it should work fine.

But then I'm left with a really large image, containing Cargo and all these build tools.

I tried to make the release target more specific and use [this image](https://github.com/messense/rust-musl-cross), but it needed openSSL.

I'll may need to invest some more time on getting multi-platform docker images working #199

**Comment by rasendubi** [comment]
Yes, this is consistent with my loader comment.

Would you like to try `rust:alpine` image for builder instead?

**Comment by joepio** [comment]
@rasendubi  yes, doing it: https://github.com/atomicdata-dev/atomic-data-rust/actions/runs/2497573779

**Comment by joepio** [comment]
Seems like `paste` [won't compile for some cc-related reason](https://github.com/atomicdata-dev/atomic-data-rust/runs/6887368382?check_suite_focus=true#step:5:697)

**Comment by joepio** [comment]
I'll try this one https://hub.docker.com/r/frolvlad/alpine-rust that contains gcc

**Comment by rasendubi** [comment]
> Seems like `paste` [won't compile for some cc-related reason](https://github.com/atomicdata-dev/atomic-data-rust/runs/6887368382?check_suite_focus=true#step:5:697)

I was able to compile with that image successfully when I added:
```dockerfile
RUN apk add --no-cache musl-dev
RUN apk add --no-cache openssl
RUN apk add --no-cache pkgconfig
RUN apk add --no-cache openssl-dev
```

**Comment by joepio** [comment]
After using a GCC image and adding openssl to the builder, the image [seems to build](https://github.com/atomicdata-dev/atomic-data-rust/runs/6888444475?check_suite_focus=true).

And it seems to run!

`docker run joepmeneer/atomic-server:rust-alpine`

**Comment by rasendubi** [comment]
`joepmeneer/atomic-server:rust-alpine` runs for me, too (although I am on M1, too 😁)
