### ISSUE TITLE
use dedicated crate to convert from HTML to Markdown

### ISSUE THREAD

**Issue by jonassmedegaard** [atomicdata-dev/atomic-data-rust#495]
If I read code correctly, then the bookmark plugin contains a HTML-to-Markdown converter.

I think it is bad for a large project to do NIH implementations like that: Please consider reusing existing crate `html2md` (which is already used elsewhere in this project) or if for some reason that is considered unsuitable then isolate the functionality as a separate reusable crate that others can use, criticize and help improve, independently of this much larger project.

**Comment by jonassmedegaard** [comment]
Oh! the bookmark plugin *is* where html2md is used - just isn't declared at the top, only deep in the code.

Sorry for the noise - then I am simply not understanding the need for all that local code, but oh well...

**Comment by joepio** [comment]
> I am simply not understanding the need for all that local code

It's a pretty complex piece of scraping used to identify the _main_ piece of an article, trying to ignore things like navigation and sidebars.

**Comment by jonassmedegaard** [comment]
then perhaps the description should mention that it is opinionated (the word "fully" misleads - regardless of being tied to indexibg not parsing)

**Comment by joepio** [comment]
Yeah, agreed. I've updated the description, thanks.

**Comment by jonassmedegaard** [comment]
nice description and internal comments now :-)
