### ISSUE TITLE
Document HTTPS setup using external TLS source

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-rust#551]
Atomic-server has built-in HTTPS support using letsencryp, but there are usecases for using external TLS source (e.g. Traeffik / Nginx / Ingress). 

To do this, users need to set these ENVS:

```ini
ATOMIC_DOMAIN=example.com
# We'll use this regular HTTP port, not the HTTPS one
ATOMIC_PORT=80
# Disable built-in letsencrypt
ATOMIC_HTTPS=false
# Since Atomic-server is no longer aware of the existence of the external HTTPS service, we need to set the full URL here:
ATOMIC_SERVER_URL=https://example.com

```

**Comment by AlexMikhalev** [comment]
I can pick this one if you are ok.

**Comment by joepio** [comment]
Thanks Alex, but I've already updated the readme. PR if anything could be improved would be very welcome ofcourse!
